# This is the config of the link checker GitHub Action (i.e., https://github.com/marketplace/actions/lychee-link-checker-action).

on: [pull_request]
name: Link Checker 
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the site
        uses: shafreenAnfar/jekyll-build-action@v5
      - name: Lychee link checker action
        id: lc
        uses: lycheeverse/lychee-action@v1
        with:
          args: --exclude twitter.com --exclude novacodecamp.org  --verbose *.md
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Link Checker Report
          path:  ./lychee/out.md  
      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}
