# This is the config of the link checker GitHub Action (i.e., https://github.com/marketplace/actions/link-checker).

on: [push]
name: Link Checker Example Command
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the site
        uses: shafreenAnfar/jekyll-build-action@v5
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -r learn swan-lake -x 0.990 -d ./_site 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Link Checker Report
          path:  ./link-checker/out.md

      #- name: SendGrid
        #uses: peter-evans/sendgrid-action@v1
        #env:
          #SENDGRID_API_KEY: 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
          #SCRIPT_FILEPATH: ./scripts/sendgrid.js
