# This is the config of the link checker GitHub Action (i.e., https://github.com/marketplace/actions/link-checker).

on: [push]
name: Link Checker Example Command
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: ./link-checker/out.md
          labels: report, automated issue
          assignees: praneesha
          env:
            LINKCHECKER_OUTPUT_DIR: ./

