# This is the config of the spell checker GitHub Action (i.e., https://github.com/marketplace/actions/check-spelling).

name: Spellcheck Action
on: push
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.5.0
      name: Spellcheck
  matrix:
    - name: Markdown
      aspell:
        lang: en
      dictionary:
      wordlists:
        - .wordlist.txt
      encoding: utf-8
  pipeline:
    - pyspelling.filters.markdown:
    - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
    sources:
      - '**/*.md'
    default_encoding: utf-8






